//
//  ArticleARViewTabView.swift
//  TestDrive
//

import SwiftUI

/// Hosts approach 5, with a picker for which model to load.
struct ArticleARViewTabView: View {
    @State private var selection = Badge.samples[3]
    @State private var source = BadgeModelSource.badgeMedallion

    // MARK: - Body

    var body: some View {
        BadgeStage(selection: $selection, notes: Self.notes) { badge in
            VStack(spacing: 12) {
                ArticleBadgeARView(badge: badge, source: source)
                    // Rebuilt when either input changes: the coordinator loads once,
                    // and the procedural fallback bakes artwork into a texture.
                    .id("\(badge.id)-\(source.rawValue)")

                sourcePicker
            }
        }
    }

    // MARK: - Private Views

    /// Switches between the USDZ models and the procedural stand-in.
    private var sourcePicker: some View {
        Picker("Model", selection: $source) {
            ForEach(BadgeModelSource.allCases) { source in
                Text(source.title).tag(source)
            }
        }
        .pickerStyle(.segmented)
        .padding(.horizontal, 8)
    }

    // MARK: - Private Helpers

    private static let notes = [
        "The Medium article's approach: ARView(.nonAR) in a UIViewRepresentable, loading a real USDZ.",
        "badge_medallion.usdz is generated by Tools/make-badge-usdz.py from the same artwork the other tabs draw — 128-segment geometry, so no faceting.",
        "1.9MB for one finish. A USDZ bakes in its textures, so shipping four finishes means four files and ~7.6MB — where approach 4 builds all four at runtime from one set of views.",
        "'rozet (missing)' is the article's own asset name: it is not here, so you see the fallback path.",
        "No image-based lighting, so the metal is duller than approach 4's — compare them directly.",
        "Pan is clamped to ±90°, so the reverse never comes round and the earned date is unreachable.",
        "The gesture lives in a UIKit coordinator, so SwiftUI state cannot drive it — the angle override does nothing here."
    ]
}

#Preview {
    ArticleARViewTabView()
}
